import { Inter } from "next/font/google";
import "./globals.css";
import { getAuthenticatedAppForUser } from "../utils/firebase/serverApp";
import Navbar from "./components/navbar";

import { AuthProvider } from "./context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}) {
  const { currentUser } = await getAuthenticatedAppForUser();

  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <AuthProvider>
            <>
              {children}
              <Navbar />
            </>
          </AuthProvider>
        </body>
      </html>
    </>
  );
}
